Fixing mypy ignores by renaming datetime import to dt_datetime, due to naming ambiguity.
error: Function "arrow.arrow.Arrow.datetime" is not valid as a type
note: Perhaps you need "Callable[...]" or a callback protocol?